# Set remote cloud hosted key to false for local machine deployments
REMOTE_CLOUD_HOSTED = false

# Assign the cloud media server host AFTER you know the deployment URL via management console
MEDIA_SERVER_CLOUD_HOST = 'asehmi-st-media-server-client-app-KEY.herokuapp.com'
MEDIA_SERVER_LOCAL_HOST = 'localhost'
MEDIA_SERVER_PORT = 8888

MAX_NUM_IMAGES = 3000
DEFAULT_NUM_IMAGES = 1000

# presets = Number of columns, Pixel width presets
# default_index = index of default to start with
[DISPLAY_PRESETS]
presets = [
    '1, 2560',
    '2, 1280',
    '3, 850',
    '4, 640',
    '5, 512',
    '10, 256',
    '20, 128',
    '40, 64'
]
default_index = 4
