# Set release to false for local machine deployments
RELEASE = false

# Assign the cloud media server host AFTER you know the deployment URL via management console
MEDIA_SERVER_CLOUD_HOST = 'asehmi-st-media-server-client-app-KEY.streamlitapp.com'
MEDIA_SERVER_LOCAL_HOST = 'localhost'
MEDIA_SERVER_PORT = 8888
